version: '1.0.{build}'
image: Visual Studio 2019
branches:
  only:
  - master
test: off
configuration: Release
before_build:
   - nuget restore src
build:
  project: src/Alturos.Yolo.sln
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: normal
deploy:
  provider: NuGet
  api_key:
    secure: V3wcx7NZrxhM9OdQ17904TeJPA2G82H8mLffwwKgqcGLghb0grm5Fsphbr9wlx64
  artifact: /.*\.nupkg/

